### ISSUE TITLE
open sidebar menu over the content

### ISSUE THREAD

**Issue by onemen** [epicweb-dev/epicshop#100]
@kentcdodds
what do you think about this?

![menu-sidebar](https://github.com/epicweb-dev/kcdshop/assets/3650909/f282a967-ce34-4045-ac87-02f0c0064756)

**Comment by kentcdodds** [comment]
I have mixed feelings about this. Part of me feels that people may use the left nav to help them find something and if it covers the content they may not be able to quickly find what they're looking for. I think let's leave it as it is currently until someone compalins.

**Comment by onemen** [comment]
![menu-overlay](https://github.com/epicweb-dev/kcdshop/assets/3650909/af61f494-8b56-49ac-ae15-5479982307ef)

we can add button/checkbox to let users toggle the menu behavior

**Comment by kentcdodds** [comment]
I'm open for doing that 👍 I'd want to use shadcn's checkbox so it looks nice :)

**Comment by onemen** [comment]
Do you want the checkbox to be visible when the menu is closed, with a tool-tip
Does the label ok? just 'Overlay Menu' or 'Overlay Menu ON' 'Overlay Menu OFF'

maybe we can use suitable icon / emoji instead of a checkbox? can you propose one?

**Comment by kentcdodds** [comment]
Yeah, I think an icon would be better for this as well.

Local storage is a fine place for this.

The more I think about it though, the more I think it's not necessary. Let's hold off.

**Comment by kentcdodds** [comment]
We're going to stick with what we have now. Thanks!
