### ISSUE TITLE
.npmrc is not present in playground folder

### ISSUE THREAD

**Issue by martijnsenden** [epicweb-dev/epicshop#167]
I tried to run `npm install` in the `playground` folder from the office. I got an error because we use a custom npm registry in Nexus at work. It didn't have all the dependencies npm was trying to install. I easily solved it by copying the `.npmrc` from the project's root to the `playground` folder. Maybe having the `.npmrc` in the playground by default would be good?

**Comment by kentcdodds** [comment]
That's probably a reasonable idea. Either that or I wonder if there's a way for me to detect when you run `npm install` in the `playground` directory so I can say "don't do this!" 😅

**Comment by martijnsenden** [comment]
Ah, I was a bit confused about how to get working with the playground, but then noticed that it's all accessible through the main app.

**Comment by kentcdodds** [comment]
After investigating this a bit, it's not really going to work since the solutions are a bit worse than the problem. Luckily this is a pretty rare issue and I've not heard it from anyone else so hopefully it's not an issue going forward.
