### ISSUE TITLE
[Idea/suggestion]: Side-by-side view for UI output

### ISSUE THREAD

**Issue by simonswiss** [epicweb-dev/epicshop#170]
Admittedly a bit niche to workshops where the visual state of the UI is changing during exercises, but I find myself wishing there was a "side-by-side" comparison view of the problem/solution.

It would be extremely useful when teaching styling techniques to allow the learner to compare the "target" UI versus what they're iterating on, without having to switch tabs.

https://github.com/epicweb-dev/kcdshop/assets/485747/152630d9-ad98-44aa-9cac-9b5713e2c0ab

**Comment by kentcdodds** [comment]
There are a lot of things that I would like to improve with regard to the UI here. As a workaround you can pull up each in their own tab (click the button next to "STOP APP") and put those tabs side-by-side.

**Comment by kentcdodds** [comment]
I'm going to close this one for now. I don't think there's a strong enough case to complicate the UI to support this.
