### ISSUE TITLE
Font Size control for texts

### ISSUE THREAD

**Issue by Noriller** [epicweb-dev/epicshop#171]
I would love to have some way to control the font size for longer texts.

Sometimes I feel a bigger font is better for reading those long texts and explanations, so I end up using zoom, which messes up everything else then I have to keep going back and forth for Zoom.

Normal view:
![image](https://github.com/epicweb-dev/kcdshop/assets/54413263/8a3ab794-8733-41e4-8658-70c808810d9b)

Zoomed view:
![image](https://github.com/epicweb-dev/kcdshop/assets/54413263/76aeff80-3827-45db-8c46-93b7a2795c08)

Font size for most of the UI is OK, but this suggestion is only for this part of the UI:
![image](https://github.com/epicweb-dev/kcdshop/assets/54413263/f5e0c0f1-2a08-4dd5-950a-cda42f3ff05a)

Giving an easier time while reading the texts, without affecting the rest of the UI, including the playground area.

**Comment by kentcdodds** [comment]
I think we could make a `/settings` page where you can control stuff like this. It can probably be just a bunch of `--css-custom-properties` which we use throughout the app. Should be pretty easy (thank you web platform!)
