### ISSUE TITLE
Persist the sidebar state

### ISSUE THREAD

**Issue by kettanaito** [epicweb-dev/epicshop#174]
## Current behavior

When I open the sidebar and refresh the page, the sidebar is closed again.

## Expected behavior

When I open the sidebar, the Workshop App remembers that choice, and if I refresh the page, the sidebar is in the state it has been before the refresh. 

> I believe we can use cookies for this.

**Comment by kentcdodds** [comment]
I've just pushed this update here: https://github.com/epicweb-dev/epicshop/commit/168c454efd8283594dadae0548991ca9fc1adbbf

Forgot to mention the issue in there. But it's now available in this release: https://github.com/epicweb-dev/epicshop/releases/tag/v5.5.0

Along with a number of other bug fixes and improvements :)

**Comment by kettanaito** [comment]
@kentcdodds, yay! Thank you! You've been rocking the Workshop app with these releases 🚀
