### ISSUE TITLE
Newly added exercise isn't visible in the UI

### ISSUE THREAD

**Issue by kettanaito** [epicweb-dev/epicshop#176]
## Current behavior

When creating a new exercise in the workshop, the UI doesn't reflect it. It's missing from the root page's list of exercises, and from the sidebar list of exercises as well. This is related to both individual exercises (steps) and top-level sections. A full refresh of the app (CTRL+C + re-run `npm run dev`) is required in order for the changes to appear in the UI.

## Actual behavior

When creating a new individual exercise, or a section, it immediately appears in any relevant UI elements without having to stop and re-run the app. 

> May be a bug rather than a feature request. Remix should be watching the glob and react to newly added files.

**Comment by kentcdodds** [comment]
Could you confirm whether this is still an issue?

**Comment by kentcdodds** [comment]
I think this has been fixed now.

**Comment by kettanaito** [comment]
Awesome! Thanks, @kentcdodds.
