### ISSUE TITLE
<CodeFile/> changes only print the warning when respective MDX changes

### ISSUE THREAD

**Issue by kettanaito** [epicweb-dev/epicshop#179]
The intention is that changes to the files referenced by `<CodeFile/>` print a warning above the component in the MDX page it's being used at. That works _but_ only if you change the actual MDX content after changing the code referenced by `<CodeFile/>`

**Comment by kentcdodds** [comment]
I'm not sure I can recommend using `<CodeFile />`. It's a pretty complicated component and there's no real way to determine whether something's changed unless you run the app so it gives a false sense of security. I think I'd rather just copy/paste whenever you need to show some code from the app, or even better use `<InlineFile />` to link to the code you want to call out.

**Comment by kentcdodds** [comment]
This was removed
