### ISSUE TITLE
Feedback: Improve "Set to playground" experience

### ISSUE THREAD

**Issue by kettanaito** [epicweb-dev/epicshop#184]
## The problem

As a student, whenever I solve an exercise and feel great about myself, I press the ">" icon to navigate to the next exercise to tackle. I _have_ not to forget to press "Set to playground" at the top of the page. I have to do that on every single exercise I progress through. 

## The solution

Improve the UX here. 

- Option 1: Assume more. Whenever the student clicks ">" to end up on the next exercise for the first time, automatically call the "Set to playground" functionality for them. 
- Option 2: Assume less. Whenever the student is about to click on the ">" icon to navigate to the next exercise for the first time, show them. a quick popup saying "Would you like to set this to Playground also?" with two options: Yes and No.
  - If they choose Yes, the App will (1) set the playground for the next exercise; (2) navigate them to the next exercise in the App.
  - If they choose No, the App will only navigate them to the next exercise. They'd have to set the code to the playground using the existing button at the top of the page.

**Comment by kentcdodds** [comment]
The problem with this is how do you distinguish between a learner who's going through the exercises and one who's going back to review something on a previous step or one who's looking for a step as a reference? Automatically changing the playground would be a big problem there and alerting every time would be really annoying.

We're pretty loud with the way we have the set to playground flashing in multiple places. I think people get used to the workflow after a while. I can't think of a way to make this better without making other use cases worse.

**Comment by kettanaito** [comment]
> The problem with this is how do you distinguish between a learner who's going through the exercises and one who's going back to review something on a previous step or one who's looking for a step as a reference? 

I agree, it's tough and it will involve a bit of guessing. However, I think it's a safe bet simply to check if this is their first time accessing that exercise page within this workshop run. Using a `sessionStorage` list of visited exercise paths is one way to do it. 

I'm generally against the "guess more" approach. I just find having to click on a button when switching to each next exercise to be distracting. Perhaps this is a good candidate for a UX revision, eventually. This can be solved on the higher user flow level:

1. I open an exercise. I can read and reference it. There is no "Set to playground" button.
2. I click "Start exercise" at the bottom. This automatically sets the playground for me. Maybe even renders a work-in-progress UI that lists the most relevant info from the previous steps, tips, and a note of encouragement.

**Comment by kentcdodds** [comment]
We could go with the "ask them with a dialog" option with an option to hold down ALT to skip the dialog and not set the playground.

**Comment by kentcdodds** [comment]
I just really worry that people would accidentally set the playground without intending to leading to them losing their work in progress.

**Comment by kentcdodds** [comment]
I think we're going to keep the current experience. Thanks for the discussion though!
