### ISSUE TITLE
"Start App" starts disconnected

### ISSUE THREAD

**Issue by jacobparis** [epicweb-dev/epicshop#196]
When starting a new app, it initially starts in a "localhost refused to connect" state but works once refreshed

https://github.com/epicweb-dev/kcdshop/assets/5633704/136c1614-eb39-4da0-ba7e-0cd136c7aa8b

**Comment by kentcdodds** [comment]
I'm not certain what's causing this and I cannot reproduce it with the example in this repo I'm afraid.

One thing that may be an issue is how we detect whether the app is ready. We hit it with `HEAD` requests and as soon as it sends back a 200 OK, then we assume it's ready for traffic. Perhaps you could check this by modifying `waitOnApp` in `node_modules/@epic-web/workshop-utils/dist/esm/process-manager.server.js` to use `GET` instead. If that fixes it then see whether there's something we can do to handle the `HEAD` request better or maybe we'll just change it to `GET`.

**Comment by kentcdodds** [comment]
I may have fixed this. Please let me know if you're still experiencing issues with the latest version
