### ISSUE TITLE
Broken/missing lesson navigation

### ISSUE THREAD

**Issue by denkasyanov** [epicweb-dev/epicshop#202]
During previous couple updates I noticed that sidebar navigation is sometimes broken and sometimes parts of it are missing.

Below is an example of missing links.

I'll add more screenshots with different kind of issues when I encounter it.

![CleanShot 2024-03-26 at 22 56 22@2x](https://github.com/epicweb-dev/kcdshop/assets/34678129/778583bb-3097-49a4-9b07-7d1de389bb07)

Steps before this issue:
1) I updated kcdshop with `npx update-epic-workshop`
2) Started it with `npm start`.
3) Watched a video in the previous lesson in full screen, marked two exercises as complete. Skipped google forms because captcha is unbearable (but I digress).
4) Pressed ">" button to open the next lesson.

Refreshing the page fixes it until next time

**Comment by kentcdodds** [comment]
Thanks for reporting! This is very odd. I cannot reproduce the issue. Could you do a little debugging for me? Check the console for errors and check the DOM over there for odd CSS rules being applied or something?

**Comment by denkasyanov** [comment]
Both Chrome console and server console show no errors. 

![CleanShot 2024-03-27 at 03 08 02@2x](https://github.com/epicweb-dev/kcdshop/assets/34678129/e4f751ad-ff18-4456-9667-bc43a30d1400)

I had to removed a bunch of "opacity" style properties to show it again.
`opacity: 0` returns after some time or after I switch to another tab and return back.

![CleanShot 2024-03-27 at 03 11 44@2x](https://github.com/epicweb-dev/kcdshop/assets/34678129/3caab610-4eb4-4f4e-abcd-e0ab990ac9d5)

Probably I shared what I found in a very dumb way. Please let me know if there is a better way to do it, I'm still on that page 😅

I also disabled uBlock Origin before that (no difference).

**Comment by denkasyanov** [comment]
Aand another one, I guess more trikier one
![CleanShot 2024-03-27 at 07 37 41@2x](https://github.com/epicweb-dev/kcdshop/assets/34678129/dbd57a20-7923-4f8c-9051-395d231997cd)


Steps:

1. I returned to the page
2. Rewatched the end of the video
3. Clicked on top left menu to open sidebar
4. One bar disappared from the open menu button
5. The sidebar doesn't open no matter how many times I click this button

This time there are errors in the chrome console

**Comment by kentcdodds** [comment]
Could you try disabling the Google translate extension?

**Comment by denkasyanov** [comment]
Completed the first lesson in the next workshop with Google translate extension disabled.
And the first issue appeared again right after I moved to the next lesson.
![CleanShot 2024-03-28 at 03 26 23@2x](https://github.com/epicweb-dev/kcdshop/assets/34678129/9f9944a8-c10d-4c04-aa9b-980dedf7b6ea)

I guess I'm ok with refreshing the page.

**Comment by kentcdodds** [comment]
Dang. This is so weird. I've not had reports from anyone else so I'm thinking it's probably something wrong with an extension you've got or something. Sorry!

**Comment by denkasyanov** [comment]
After some additional testing, I believe the offending extension is 1Password https://chromewebstore.google.com/detail/1password-%E2%80%93-password-mana/aeblfdkhhhdcdjpifhhbdiojplfjncoa

I completed a couple of lessons without 1Password extension in freshly installed Brave browser. Didn't use this browser before. No issues with the sidebar.

Tried different combinations of my usual extensions and very soon after I enable 1Password (with or with no other extensions) the issues appear in Brave as well.

I don't know the exact order of steps to reliably reproduce it.

However, this time, right after I installed it in Brave (and it connected to 1Passowrd desktop app) and tried to close the sidebar, this happened
![CleanShot 2024-03-31 at 02 02 40@2x](https://github.com/epicweb-dev/kcdshop/assets/34678129/5db46725-352e-4828-9b2c-0ccad6e06f3a)

Something like this happened in Chrome as well.

**Comment by denkasyanov** [comment]
Actually, it happens even without extensions.

I'm in the DATA MODELING DEEP DIVE workshop.

First scenario, in which everything works fine.

- I'm on page "Updating Data" (http://localhost:5639/07)
- Click on "SQL" section in the sidebar
- SQL section reveals with all lessons visible

Second scenario

- I'm on page "Updating Data" (http://localhost:5639/07)
- Click "Elaboration" lesson in this section (http://localhost:5639/07/finished)
- The lesson is completed
- Click two times (uncomplete -> complete)
- See the confetti animation
- Click the right arrow button to go to the next lesson (1)
- Boom, items in the menu are invisible (2)

---
(1)
![CleanShot 2024-03-31 at 02 46 20@2x](https://github.com/epicweb-dev/kcdshop/assets/34678129/9522f536-ec1a-4d2b-8a66-d091b95156a5)
---
(2)
![CleanShot 2024-03-31 at 02 48 59@2x](https://github.com/epicweb-dev/kcdshop/assets/34678129/09549140-c413-4bdf-86c0-37430ad9f86f)
---
Notes:
- If I click only one time to uncomplete elaboration (no confetti) menu works fine
- Above scenarios were tested in Brave browser. No extensions at all, even disabled.
- Exactly the same thing is happening in Safari
- Looks like confetti in any other lessons leads to the same issue with menu. Also, when navigating via sidebar menu, not necessarily using the button under the complete lesson checkbox. Reproduced both in pristine Brave and regular Safari.

**Comment by kentcdodds** [comment]
Ah! I reproduced it using the steps you provided! Phew! Thank you for coming up with these steps.

I see some relevant errors in the console:

<img width="602" alt="animation-related errors" src="https://github.com/epicweb-dev/kcdshop/assets/1500684/28e11146-ab5b-4927-b39a-6e31c50cbdd2">

This is helpful. Thank you!

**Comment by d3vl1m3** [comment]
Perfect. Yeah. I found the same issue recently as well. Great to see it's already been highlighted :)

**Comment by kentcdodds** [comment]
I think this has been fixed. Anyone care to verify?
