### ISSUE TITLE
"Unsupported" test type toast in the UI

### ISSUE THREAD

**Issue by kettanaito** [epicweb-dev/epicshop#211]
The "Tests" tab in the Mocking Techniques workshop looks like this:

![Screenshot 2024-07-24 at 14 51 46](https://github.com/user-attachments/assets/90e4f8b8-0541-4c22-b0e2-1553535ec0f9)

For some reason, the `app.test.type` for the tests there is (probably) `none` (expected `browser`). 

Perhaps there's a way to disable the Tests tab altogether? While there's nothing Node-specific in my tests, @kentcdodds mentioned running tests may not behave entirely as expected for non-browser tests.

**Comment by kentcdodds** [comment]
Ok, so this is why you're getting this error:

https://github.com/epicweb-dev/epicshop/blob/8c25a3566a0c76b38428a91887ee548fcd7423d2/packages/workshop-app/app/routes/_app%2B/app.%24appName%2B/test.%24testName.ts#L29

If the tests are browser-based, but the app is not then you'll get this error.

I think the solution is indeed to have a mechanism for disabling the test tab. I've really wanted to avoid configuration like this, but I think we should probably just have a config option for it.

**Comment by kentcdodds** [comment]
Forgot to mention this issue, but it's fixed: https://github.com/epicweb-dev/epicshop/commit/5708376c8ea62f7e7723539a4b7288caeb89d7db

**Comment by kettanaito** [comment]
Thank you, @kentcdodds! Confirm it working.
