### ISSUE TITLE
Add padding to "No changes" in diff

### ISSUE THREAD

**Issue by kettanaito** [epicweb-dev/epicshop#212]
This is minor UI suggestion: to add a consistent padding to the "No changes" label when the diff'ed file was renamed. 

![Screenshot 2024-07-25 at 14 26 10](https://github.com/user-attachments/assets/4bb83bd2-e67d-43ab-9da6-11c99f3226c0)

**Comment by kentcdodds** [comment]
This would be good!

**Comment by kettanaito** [comment]
@kentcdodds, I can look into this this week! Shouldn't be a problem to fix.

**Comment by kettanaito** [comment]
I've fixed that styles of that Markdown snippet to this:

<img width="692" alt="Screenshot 2024-08-01 at 19 23 35" src="https://github.com/user-attachments/assets/a79bb9dc-c897-4646-9471-d1c9667659a9">

- Added the same consistent padding;
- Marked the text as muted to highlight it's not something to pay attention to;
- Added bottom border to visually separate the standalone string from the following `<details>` of the next file in the diff.
