### ISSUE TITLE
epic_ws.js is 404 when opening up playground in separate window

### ISSUE THREAD

**Issue by htulipe** [epicweb-dev/epicshop#221]
Hello,

When I'm opening up the playground on a separate window (`http://localhost:5639/app/playground`) I noticed there was no live reloading upon file save. Looking at the network panel in dev tools I saw a 404 for `epic_ws.js`.

Comparing with the iframe embedded playground (which does has live reload) I saw the request for `epic_ws.js` differs:

- embedded playground asks for `http://localhost:5639/app/playground/epic_ws.js` => 200 OK
- external playground asks for `http://localhost:5639/app/epic_ws.js` => 404

I'm circumventing the issue by updating `playground/index.html` and changing `<script type="module" src="epic_ws.js"></script>` to `<script type="module" src="playground/epic_ws.js"></script>`. It breaks the embedded playground though.

Context:
 - I'm on "get started with react" workshop
 - app is run through Windows Subsystem for Linux

Thanks in advance!

**Comment by kentcdodds** [comment]
Hello @htulipe,

Thanks for this. Can you tell me if this is happening on all exercises or just one in particular?

**Comment by htulipe** [comment]
Hi, I would say all exercises. I'm on the "Get started with React" workshop and went up until "Custom Component" chapter and I had this issue on every single exercise so far.

**Comment by kentcdodds** [comment]
This is quite odd since I cannot reproduce this myself. What browser are you using?

**Comment by htulipe** [comment]
I'm on Firefox but can replicate also on Chrome. I don't think it's a browser issue. What's the expected behavior? Should the server accept both `app/epic_ws.js` and `app/playground/epic_ws.js` or should the generated script URL should always be `app/playground/epic_ws.js` ?

**Comment by htulipe** [comment]
Ok got it, the error will occur if you omit the last slash in the URL when accessing the playgroud:

- http://localhost:5639/app/playground -> KO
- http://localhost:5639/app/playground/ -> OK

It makes sense when you think about it but it's troublesome nevertheless. A solution might be to use absolute URL in the src attribute `<script type="module" src="/app/playground/epic_ws.js"></script>`. This will work but that's not ideal.

**Comment by kentcdodds** [comment]
Ah yes, this is tricky and only applies for the first 4 exercises where we're working in an `index.html` directly. For future exercises, the `index.html` is generated for you and I can add `<base href="/app/playground/" />` to the generated html file. I can't do this earlier because I want to avoid changing the `index.html` file you're editing, and I also can't place that in the source because it will be different for when the app is in the playground tab vs the problem/solution tabs.

So I think I'm just gonna have to leave it as-is and hopefully not many people run into this issue.

But I'll keep it in mind for future people who are confused 😅 Thanks!

**Comment by htulipe** [comment]
No problem, happy to help. May I suggest adding a link in the UI that leads to the external playground? That way most of your users will access it through that and you'll decrease the risk of having someone typing the URL himself.

**Comment by kentcdodds** [comment]
There is a link. In the bottom right corner

**Comment by htulipe** [comment]
My bad :D
