### ISSUE TITLE
Save selected video quality

### ISSUE THREAD

**Issue by tonilaukka** [epicweb-dev/epicshop#222]
Playback speed and caption settings are saved, but quality setting is not. It would be nice if this would be saved too, so you don't have change it everytime you advance to the next lesson.

https://discord.com/channels/715220730605731931/1289897990798049343/1289897990798049343

**Comment by tonilaukka** [comment]
I was experimenting with the EpicShop app and encountered an issue, but I couldn't find an event in the RealMuxPlayer for quality changes. After reading the Mux Player documentation, I learned that quality changes automatically when necessary, such as when switching to picture-in-picture mode or fullscreen. It may take a few seconds, so forcing the change might be quicker. This is likely also related to your bandwidth.

I couldn't find a way to save the quality preference just by changing the player settings. You could store this in the profile as the preferred quality and set a min_resolution property for the player accordingly, but I'm not sure if it's worth it.

You could also set the rendition_order to desc so the video starts in the highest quality (4K), but I don't see the point since the player is so small to begin with.

Sources:
https://www.mux.com/blog/more-tools-to-control-playback-behavior-min-resolution-and-rendition-order#rendition_order
https://docs.mux.com/guides/modify-playback-behavior#availiable-playback-modifiers

**Comment by kentcdodds** [comment]
Ah, I figured there was a reason I didn't have this support to begin with. Seems like it's probably better to let Mux decide what's best based on the size of the video on screen and the user's network speed.

Thanks for doing some research on this!
