### ISSUE TITLE
Tests are not updating

### ISSUE THREAD

**Issue by ezekeal** [epicweb-dev/epicshop#223]
When I save a change in the playground folder, the playground tab in the app updates.

Expected behavior:
The tests should update in the same way when selecting "rerun" and test against the latest save

Current behavior:
The tests continue to run against the first version tested against as if it caches after the first test is run

Current workaround:
kill and rerun the react-fundamentals app in the terminal

https://github.com/user-attachments/assets/be51ae2e-0855-41a7-9512-37872a166982

**Comment by kentcdodds** [comment]
I think I may have fixed this. Could you please let me know if you experience this with the latest version?

Thanks!

**Comment by kentcdodds** [comment]
Whoops, just reproduced again. Nevermind 😅

**Comment by kentcdodds** [comment]
Finally figured this one out. It was tricky! Please let me know if you have trouble with it.
