### ISSUE TITLE
`update-epic-workshop` thinks I have no internet connection, but I do

### ISSUE THREAD

**Issue by andrerfcsantos** [epicweb-dev/epicshop#227]
I do have an internet connection, but `update-epic-workshop` is failing saying I don't:

```
❯  npx update-epic-workshop
❌ Error updating local repo: ❌ No internet connection. Cannot check for updates.
```

After reading the code on how the scripts check for internet connections, I see it tries to resolve a dns for `example.com`. Well, for some reason it seems my network is not being able to access `example.com`. I though it might be some config on my computer, but I can't also access `example.com` on my phone (connected to the same network as my pc).

While the fact I can't access `example.com` is weird, maybe it should be worth considering other ways of checking if an user has an internet connection? Like a ping to google or to npm itself?

**Comment by kentcdodds** [comment]
pinging npm sounds like a better solution. Thanks for the idea! https://github.com/epicweb-dev/epicshop/commit/93d7fb1db90e28b73d92ce3a220cd59db39ad4e3
