### ISSUE TITLE
Automatically Save Playground Files for Course Progress

### ISSUE THREAD

**Issue by larissapissurno** [epicweb-dev/epicshop#229]
I often take notes on playground files and noticed that manually saving them can be tedious. To streamline this, I've created a script that saves the playground into a new folder with the command `npm run save-playground`, making it easier to save progress throughout the course.

I have drafted a PR for this on [epicweb-dev/advanced-react-patterns](https://github.com/epicweb-dev/advanced-react-patterns), but I guess it would be better to drop that on the workshop app. 

Would this be helpful for others? Looking forward to your thoughts. Thanks in advance! 🙌

PR Link: https://github.com/epicweb-dev/advanced-react-patterns/pull/132/files

**Comment by kentcdodds** [comment]
Thanks for the suggestion! I've added a few preference to the `/preferences` route (you can find a link to this on your `/account` page) which will auto-save the playground each time you click "set to playground"

<img width="913" alt="image" src="https://github.com/user-attachments/assets/91213479-2cb6-42a7-9197-0357d97616f1">

**Comment by larissapissurno** [comment]
awesome @kentcdodds, thx!
